### ISSUE TITLE
Add recipe inheritance

### ISSUE THREAD

**Issue by rhysrevans3** [cedadev/stac-generator#78]
Allow one recipe to "inherit" extraction methods from another recipe.

**Comment by rhysrevans3** [comment]
Possible config:
``` 
- method: inherit
   inputs:
       from: /path/to/file
       methods:
         - defaults
```
